include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
    unused_local_variable: warning

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_final_fields: true
