name: azkar_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  percent_indicator: ^4.2.5
  fluttertoast: ^8.2.0
  share_plus: ^11.0.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  vibration: ^3.1.3
  flutter_timezone: ^4.1.1
  intl:
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  #flutter_qiblah: ^3.1.0+1
  #geolocator: ^13.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/azkar.json


