name: azkar_application  # اسم المشروع

description: "This is App adhkar UI/UX and provider... theme... language"  
# وصف المشروع، مجرد نص توضيحي، لا يؤثر على عمل التطبيق

publish_to: 'none'  
# يمنع نشر المشروع على pub.dev، يعني المشروع محلي أو خاص

version: 1.1.2+1  
# رقم نسخة التطبيق:
# 1.1.2 → major.minor.patch
# +1    → رقم البناء الداخلي (build number)

environment:
  sdk: ">=3.5.0 <4.0.0"  
  # إصدار Dart المطلوب لتشغيل المشروع

dependencies:
  flutter:
    sdk: flutter  # إطار عمل Flutter الأساسي

  # Localization
  flutter_localizations:
    sdk: flutter  # لدعم الترجمة واللغات

  # Material Icons
  cupertino_icons: ^1.0.8  # أيقونات iOS وMaterial

  # State management
  provider: ^6.1.2  # لإدارة الحالة

  # Local storage
  shared_preferences: ^2.3.2  # لتخزين البيانات محليًا

  # Timezone & notifications
  flutter_timezone: ^4.1.1
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.3  # للتنبيهات حسب المنطقة الزمنية

  # UI utils
  percent_indicator: ^4.2.5  # لعرض مؤشرات النسبة المئوية

  # Device features
  fluttertoast: ^8.2.0  # عرض رسائل قصيرة (Toast)
  share_plus: ^11.0.0   # مشاركة المحتوى
  vibration: ^3.1.3     # الاهتزاز
  url_launcher: ^6.2.6  # فتح الروابط والتطبيقات الخارجية

dev_dependencies:
  flutter_test:
    sdk: flutter  # أدوات اختبار المشروع
  flutter_lints: ^4.0.0  # قواعد تنسيق الكود (Linting)

flutter:
  uses-material-design: true  # استخدام أيقونات وTheme الـ Material
  assets:
    - assets/json/adhkar.json  # ملفات المشروع الثابتة (مثل JSON)
