import 'package:azkar_application/features/azkar/presentation/widgets/azkar_list_view.dart';
import 'package:azkar_application/features/search/presentation/azkar_search_delegate.dart';
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    final items = [
      {"title": "أذكار الصباح والمساء", "type": "morning_evening"},
      {"title": "أذكار النوم", "type": "sleep"},
      {"title": "أذكار الاستيقاظ", "type": "wake_up"},
      {"title": "دعاء دخول الخلاء", "type": "enter_toilet"},
      {"title": "دعاء الخروج من الخلاء", "type": "exit_toilet"},
      {"title": "دعاء قبل الوضوء", "type": "pre_wudu"},
      {"title": "دعاء بعد الوضوء", "type": "post_wudu"},
      {"title": "دعاء الخروج من المنزل", "type": "leave_home"},
      {"title": "دعاء دخول المنزل", "type": "enter_home"},
      {"title": "دعاء الذهاب إلى المسجد", "type": "going_mosque"},
      {"title": "دعاء دخول المسجد", "type": "enter_mosque"},
      {"title": "دعاء الخروج من المسجد", "type": "exit_mosque"},
      {"title": "أذكار الأذان", "type": "adhan"},
      {"title": "دعاء لبس الثوب", "type": "putting_clothes"},
      {"title": "دعاء لبس الثوب الجديد", "type": "new_clothes"},
      {"title": "ما يقال عند لبس الثياب", "type": "wearing_advice"},
      {"title": "دعاء الاستفتاح في الصلاة", "type": "start_prayer"},
      {"title": "ذكر الركوع", "type": "rukoo"},
      {"title": "ذكر الرفع من الركوع", "type": "rise_rukoo"},
      {"title": "ذكر السجود", "type": "sujood"},
      {"title": "ذكر بين السجدتين", "type": "between_sujood"},
      {"title": "دعاء سجود التلاوة", "type": "sujood_recitation"},
      {"title": "التشهد", "type": "tashahhud"},
      {"title": "الصلاة على النبي بعد التشهد", "type": "salawat_tashahhud"},
      {"title": "دعاء بعد التشهد الأخير", "type": "dua_final_tashahhud"},
      {"title": "أذكار ما بعد الصلاة", "type": "post_prayer"},
      {"title": "دعاء صلاة الاستخارة", "type": "istikhara"},
      {"title": "دعاء التقلب في الليل", "type": "night_turning"},
      {"title": "دعاء الخوف أو القلق في النوم", "type": "sleep_fear"},
      {"title": "دعاء الرؤيا", "type": "dream"},
      {"title": "دعاء القنوت في الوتر", "type": "witr_qunoot"},
      {"title": "دعاء بعد الوتر", "type": "after_witr"},
      {"title": "دعاء الهم والحزن", "type": "anxiety"},
      {"title": "دعاء الكرب", "type": "distress"},
      {"title": "دعاء مواجهة العدو والظالم", "type": "enemy"},
      {"title": "دعاء الخوف من الطاغية", "type": "tyrant"},
      {"title": "دعاء لعن العدو", "type": "curse_enemy"},
      {"title": "دعاء الخوف من الناس", "type": "fear_people"},
      {"title": "دعاء الوسوسة الشيطانية", "type": "satan_whispers"},
      {"title": "دعاء قضاء الدين", "type": "debt"},
      {"title": "دعاء الوسوسة في الصلاة والقراءة", "type": "prayer_whispers"},
      {"title": "دعاء تعسّر الأمور", "type": "difficulty"},
      {"title": "دعاء التوبة", "type": "repentance"},
      {"title": "دعاء طرد الشيطان والوساوس", "type": "expel_satan"},
      {"title": "دعاء إذا غُلب على أمره", "type": "overpowered"},
      {"title": "دعاء تهنئة المولود", "type": "newborn"},
      {"title": "دعاء تحصين الأولاد", "type": "children_protection"},
      {"title": "دعاء عيادة المريض", "type": "sick"},
      {"title": "دعاء من يئس المريض", "type": "patient_hope"},
      {"title": "تلقين المحتضر", "type": "dying"},
      {"title": "دعاء عند المصيبة", "type": "calamity"},
      {"title": "دعاء إغماض الميت", "type": "dead_eyes"},
      {"title": "دعاء الميت في الصلاة", "type": "dead_prayer"},
      {"title": "دعاء بعد الصلاة على الميت", "type": "post_dead_prayer"},
      {"title": "دعاء التعزية", "type": "condolence"},
      {"title": "دعاء دخول القبر", "type": "grave_entry"},
      {"title": "دعاء بعد الدفن", "type": "after_burial"},
      {"title": "دعاء زيارة القبور", "type": "visit_graves"},
      {"title": "دعاء الريح", "type": "wind"},
      {"title": "دعاء الرعد", "type": "thunder"},
      {"title": "دعاء الاستسقاء", "type": "rain_request"},
      {"title": "دعاء نزول المطر", "type": "rain"},
      {"title": "دعاء بعد المطر", "type": "after_rain"},
      {"title": "دعاء رؤية الهلال", "type": "moon"},
      {"title": "دعاء الإفطار", "type": "iftar"},
      {"title": "دعاء قبل الطعام", "type": "before_food"},
      {"title": "دعاء بعد الطعام", "type": "after_food"},
      {"title": "دعاء الضيف للمضيف", "type": "guest"},
      {"title": "دعاء طلب الطعام أو الشراب", "type": "request_food"},
      {"title": "دعاء الأكل عند أحد", "type": "eat_house"},
      {"title": "دعاء الصائم عند الطعام", "type": "fasting_food"},
      {"title": "ما يقوله الصائم إذا شُتم", "type": "fasting_insult"},
      {"title": "دعاء رؤية بواكير الثمر", "type": "first_fruits"},
      {"title": "دعاء العطاس", "type": "sneeze"},
      {"title": "ما يقال للكافر إذا عطس", "type": "sneeze_kafir"},
      {"title": "دعاء للمتزوج", "type": "married"},
      {"title": "دعاء الجماع", "type": "marital"},
      {"title": "دعاء الغضب", "type": "anger"},
      {"title": "دعاء مواجهة البلاء", "type": "trials"},
      {"title": "آداب الجلوس", "type": "sitting_etiquette"},
      {"title": "كفارة المجلس", "type": "sitting_expiation"},
      {"title": "دعاء لمن قال غفر الله لك", "type": "forgiveness"},
      {"title": "دعاء لمن صنع إليك معروفاً", "type": "good_deed"},
      {"title": "الاستعاذة من الدجال", "type": "dajjal"},
      {"title": "دعاء لمن قال أحبك في الله", "type": "love_allah"},
      {"title": "دعاء لمن عرض عليك مالاً", "type": "offer_wealth"},
      {"title": "دعاء الدين عند القضاء", "type": "loan_court"},
      {"title": "دعاء الخوف من الشرك", "type": "shirk_fear"},
      {"title": "دعاء لمن قال بارك الله فيك", "type": "bless_you"},
      {"title": "دعاء اجتناب الطيرة", "type": "superstition"},
      {"title": "دعاء ركوب الدابة", "type": "riding"},
      {"title": "دعاء السفر", "type": "travel"},
      {"title": "دعاء دخول القرية أو البلدة", "type": "enter_village"},
      {"title": "دعاء دخول السوق", "type": "enter_market"},
      {"title": "دعاء كرب السفر", "type": "ride_trouble"},
      {"title": "دعاء المسافر للمقيم", "type": "traveler_to_resident"},
      {"title": "دعاء المقيم للمسافر", "type": "resident_to_traveler"},
      {"title": "التكبير والتسبيح في السفر", "type": "travel_takbeer"},
      {"title": "دعاء المسافر عند السحر", "type": "travel_sahar"},
      {"title": "دعاء نزول مكان في السفر", "type": "travel_landing"},
      {"title": "دعاء الرجوع من السفر", "type": "return_travel"},
      {"title": "دعاء عند سماع خبر سار أو محزن", "type": "good_bad_news"},
      {"title": "فضل الصلاة على النبي", "type": "salawat_fadl"},
      {"title": "نشر السلام", "type": "spread_salam"},
      {"title": "رد السلام على غير المسلم", "type": "nonmuslim_salam"},
      {"title": "دعاء صياح الديك ونهيق الحمار", "type": "animal_sounds"},
      {"title": "دعاء نباح الكلب بالليل", "type": "dog_bark"},
      {"title": "دعاء لمن آذاك", "type": "harmed"},
      {"title": "ما يقوله المسلم إذا مُدح", "type": "praise"},
      {"title": "ما يقوله المسلم إذا زُكي", "type": "zaki"},
      {"title": "دعاء الإحرام في الحج والعمرة", "type": "ihram"},
      {"title": "التكبير عند الحجر الأسود", "type": "black_stone"},
      {"title": "الدعاء بين الركن اليماني والحجر", "type": "yemeni_corner"},
      {"title": "الوقوف على الصفا والمروة", "type": "safa_marwa"},
      {"title": "دعاء يوم عرفة", "type": "arafah"},
      {"title": "الذكر عند المشعر الحرام", "type": "mashar_haram"},
      {"title": "التكبير مع رمي الجمار", "type": "jamarat"},
      {"title": "دعاء التعجب والسرور", "type": "amazement"},
      {"title": "دعاء عند حدوث أمر طيب", "type": "good_event"},
      {"title": "دعاء عند الألم", "type": "pain"},
      {"title": "دعاء الخوف من العين أو الضرر", "type": "eye_harm"},
      {"title": "دعاء عند الفزع", "type": "fright"},
      {"title": "دعاء الذبح", "type": "slaughter"},
      {"title": "دعاء ضد الجن", "type": "evil_jinn"},
      {"title": "دعاء التوبة والاستغفار", "type": "repentance_istighfar"},
      {"title": "التسبيح والتحميد والتهليل والتكبير", "type": "tasbeeh"},
      {"title": "كيف كان النبي يثني", "type": "prophet_praise"},
      {"title": "أنواع الذكر والآداب الجامعة", "type": "good_etiquette"},
    ];

    return Scaffold(
      appBar: AppBar(
        title: const Text('الأذكار'),
        // leading: IconButton(
        //   onPressed: () {},
        //   icon: const Icon(Icons.notifications_active_outlined, size: 26),
        // ),
        actions: [
          IconButton(
            icon: const Icon(Icons.search, size: 26),
            onPressed: () => showSearch(
              context: context,
              delegate: AzkarSearchDelegate(),
            ),
          ),
        ],
      ),
      body: AzkarListView(items: items),
    );
  }
}
